services:
  # Base de données MySQL 8.0
  database:
    image: mysql:8.0
    container_name: sf_restaurant_db
    restart: unless-stopped
    env_file:
      - .env.docker
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - sf_restaurant_network

  # PHP + Apache
  web:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: sf_restaurant_web
    restart: unless-stopped
    working_dir: /var/www/html
    env_file:
      - .env.docker
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
    networks:
      - sf_restaurant_network
    depends_on:
      - database

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: sf_restaurant_phpmyadmin
    restart: unless-stopped
    env_file:
      - .env.docker
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
    ports:
      - "8081:80"
    networks:
      - sf_restaurant_network
    depends_on:
      - database

volumes:
  db_data:


networks:
  sf_restaurant_network:
    driver: bridge
